### ISSUE TITLE
Use of a Spring in 2 Dimensions

### ISSUE THREAD

**Issue by chrisgonzalez** [iamralpht/gravitas.js#3]
First- thank you for this library. This is the closest thing I've found to a useful js physics library for my UI work. Hacking my way through it, I've encountered a dark corner of my own ignorance with a use-case that I feel should be simple.

What I'm trying to accomplish is to move a container on touch end from position A (wherever the touch end event occured) to position B ( let's say, (100, 100)) using a Spring to allow it to be "pulled" to that new location. 

Going through the examples, I've not been able to tease out a consistent solution using the createAnimation() function you've included. In this effort I am using Hammer.js for it's wonderful velocity calculations.

Here is my touchend code:

```
var simulation = new Gravitas.Spring(1, 400, 40);
simulation.snap(self._x);
simulation.setEnd(100, e.velocityX);

self._xSimulation = new ExtractAxis(simulation, 1, self._x);
self._ySimulation = new ExtractAxis(simulation, 1, self._y);

self._animation = Gravitas.createAnimation(simulation, self.update);
```

I'm using the ExtractAxis function from your 2DScrolling demo:

```
var ExtractAxis = function (simulation, multiplier, start) {
    this._simulation = simulation;
    this._multiplier = multiplier;
    this._startX = start;

    this.x = function(dt) {
        return this._startX + this._simulation.x(dt) * this._multiplier;
    }

    this.dx = function() {
        return this._simulation.dx() * this._multiplier;
    }

    this.done = function() { return this._simulation.done(); }

}
```

And the update function referenced above:

```
this.update = function () {
    if (self._animation) {
        self._x = self._xSimulation.x();
        self._y = self._ySimulation.x();
    }

    self.element.css({
        top: self._y + 'px',
        left: self._x + 'px'
    });
}
```

I feel like I'm missing something basic here- any guidance is greatly appreciated!

**Comment by iamralpht** [comment]
You might need to do
`self._animation = Gravitas.createAnimation(simulation, self.update.bind(self));`

Does update ever get called as it is?

**Comment by chrisgonzalez** [comment]
So update was getting called only once- I have modified the above touchend code to something like this:

```
var simulationX = new Gravitas.Spring(1, 400, 40);
simulationX.snap(0);
simulationX.setEnd(e.velocityX * 100, e.velocityX);

var simulationY = new Gravitas.Spring(1, 400, 40);
simulationY.snap(0);
simulationY.setEnd(e.velocityY * 100, e.velocityY);

self._xSimulation = new ExtractAxis(simulationX, 1, self._x);
self._ySimulation = new ExtractAxis(simulationY, 1, self._y);

self._animation = Gravitas.createAnimation(simulationX, self.update.bind(self));
```

What I'm seeing now is that when the drag ends, the container springs in the opposite direction for e.velocity \* 100 pixels for each axis. This appears to be relative to the container's position when the touchend is fired.

Modifying my question slightly- how can I get the container to be drawn back to a specific on-screen coordinate with a spring-like behavior, say (100,100), in a behavior similar to your Floating Action Button demo. 

Do I need to use multiple simulations for this (like gravity until it reaches the coordinate, then switch to a spring)?

**Comment by chrisgonzalez** [comment]
Digging into your example a bit more, I now see the path :)

For anyone interested in this kind of thing, here is the approach I found:

For a container that is done dragging at point (x1, y1) that needs to be "sprung" to a point (x0, y0), on touchend:

```
// Create a new spring simulation
var simulation = new Gravitas.Spring(1, 400, 20);
simulation.snap(0);
simulation.setEnd(1);

self._startX = parseInt( self.element.css('left') );
self._startY = parseInt( self.element.css('top') );

self._xSimulation = simulation;
self._ySimulation = simulation;

self._animation = Gravitas.createAnimation(simulation, self.update.bind(self));
```

By creating a spring that starts at 0 and ends at 1, we can use this to normalize the animation between any two coordinates.

On update:

```
self._x = self._startX - self._xSimulation.x() * (self._startX - self._destinationX);
self._y = self._startY - self._ySimulation.x() * (self._startY - self._destinationY);

self.element.css({
    top: self._y + 'px',
    left: self._x + 'px'
});
```

The basic math here is:

```
x = x1 - spring.x() * (x1 - x0)
y = y1 - spring.x() * (y1 - y0)
```

Where spring.x() will return a normalized value from 0 - 1 with a spring-like behavior.

Thank you again sir for a useful library :)

**Comment by iamralpht** [comment]
Neat! I'm glad you got it working :). For some reason Hammer's velocity goes in the other direction to what I'd expect.

I normally end up making my springs go between 0..1 too.

Currently Gravitas has no documentation beyond the examples. What would have been the most useful documentation to help you get started? (e.g.: API docs or a general explainer on the specifics of using Spring, Gravity, etc)

**Comment by chrisgonzalez** [comment]
I'm a big fan of examples- I think some simple-case examples for how to use springs, gravity, fall, and friction in a consistent way would be immensely helpful in getting oriented.

These examples plus some basics on the various options (and what they mean) for each of your simulations would have been very helpful. 

That said, your code is awesomely clean and very well commented. Can't wait to dig in a little more and put it to real use!

**Comment by arnold-almeida** [comment]
I was playing with this yesterday. 

I setup the basic 2D Scrolling in the context of a corova / react mobile app.

Its pretty amazing stuff. Will be interesting to see how it preforms on mobile devices.

When i get some time this week ill export what i have so its easier to experiment and add demos, i spent a good couple of hours or so just having to get the source working correctly.

@iamralpht In regards to the docs
- I think if this is abstracted down to some generalised react components it would be amazing.
- A good starting point would be http://framerjs.com/docs/ as i believe it provides a simple vernacular

ie. 
Layout === BackgroundLayer
Box === Layer
Box.children === Layer.sublayer

**Comment by iamralpht** [comment]
Hi Arnold,

I can't wait to see what you've made! Slalom is my attempt at simplifying the process of creating physics-based interactions; 2D scrolling there becomes much simpler: https://github.com/iamralpht/slalom/blob/master/examples/2DScrolling/2DScrolling.js

But you can't express all the same kinds of systems with Slalom (because it's based on linear constraints) so you still need to drop down to Gravitas directly for those.

I'm planning on integrating Slalom with React, and I'll probably get to that pretty soon because I bet it changes the way Slalom systems are described...

The Framer docs are pretty beautiful, thanks for linking to them :).

**Comment by arnold-almeida** [comment]
Hey @iamralpht 

I don't think its anything too special!

https://github.com/arnold-almeida/react-experiments
